# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [majkasgurunu, vugule1]
patreon: # Replace with a single Patreon andymarkovic
open_collective: # Replace with a single Open Collective andymarkovic
ko_fi: # Replace with a single Ko-fi anndroyd369
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay andymarkovic
issuehunt: # Replace with a single IssueHunt anndroyd369
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar andymarkovic
buy_me_a_coffee: # Replace with a single Buy Me a Coffee andymarkovic
thanks_dev: # Replace with a single thanks.dev andymarkovic
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
