// Main entry — the client decodes with the codama engine by default ('./codama' exports the pieces
// for explicit wiring or a custom provider).
export {
    createIdlClient,
    createIdlMetaClient,
    type IdlClient,
    type IdlClientOptions,
    type IdlMetaClient,
    type IdlMetaClientOptions,
    isAnchorStandard,
    isCodamaStandard,
    tryCreateIdlClient,
    type TryCreateIdlErrorCode,
    tryCreateIdlMetaClient,
} from './client.js';
export {
    type DecodedEntry,
    type DecodedEntryOf,
    type EntryPath,
    findEntry,
    findEntryOfKind,
    getDecodedEntries,
    getEnumVariantName,
    joinPath,
} from './entries/index.js';
export type { AccountDataOf, AccountsDataOf, AsDecoded, InstructionDataOf } from './infer/index.js';
export {
    getIdlProgramVersion,
    getIdlStandard,
    getIdlVersion,
    isAnchorIdl,
    isCodamaIdl,
    isLegacyAnchorIdl,
    isSupportedIdl,
} from './detect/index.js';
export {
    err,
    getIdlErrorMessage,
    IDL_ERROR__ACCOUNT_DECODE_FAILED,
    IDL_ERROR__DECODE_KIND_MISMATCH,
    IDL_ERROR__DECODE_UNIMPLEMENTED,
    IDL_ERROR__IDL_ADDRESS_MISMATCH,
    IDL_ERROR__IDL_FETCH_FAILED,
    IDL_ERROR__IDL_NOT_FOUND,
    IDL_ERROR__IDL_PARSE_FAILED,
    IDL_ERROR__INSTRUCTION_DECODE_FAILED,
    IDL_ERROR__MISSING_DECODE_HANDLER,
    IDL_ERROR__PROGRAM_ADDRESS_REQUIRED,
    IDL_ERROR__UNSUPPORTED_IDL_FORMAT,
    IdlError,
    type IdlErrorCode,
    type IdlErrorContext,
    isIdlError,
    ok,
    type Result,
} from './errors.js';
export {
    buildInstructionNameResolver,
    buildInstructionNameTable,
    buildProgramName,
    type InstructionNameEntry,
    type InstructionNameResolver,
    type InstructionNameTable,
    matchInstructionName,
} from './names/index.js';
export {
    type AccountDecode,
    type AccountDecodeFor,
    type AccountHandlers,
    type AnchorDecodedAccount,
    type AnchorDecodedInstruction,
    type AnchorIdl,
    type AnchorV00Idl,
    type AnchorV01Idl,
    type CodamaDecodedAccount,
    type CodamaDecodedInstruction,
    type CodamaIdl,
    type CodamaIdlInput,
    type FallbackDecoder,
    type FallbackDecoderOptions,
    IdlStandard,
    type IdlFetcher,
    type IdlVersion,
    type IdlDecodeProvider,
    type InstructionDecode,
    type InstructionDecodeFor,
    type InstructionHandlers,
    type SupportedIdl,
    type SupportedIdlInput,
    type UnknownArmErrors,
    unwrap,
} from './types.js';
