import { Autocomplete } from '@components/shared/ui/autocomplete';
import { Badge } from '@components/shared/ui/badge';
import { Label } from '@components/shared/ui/label';
import { Tooltip, TooltipContent, TooltipTrigger } from '@components/shared/ui/tooltip';
import type { InstructionAccountData } from '@entities/idl';
import Image from 'next/image';
import { forwardRef, useState } from 'react';
import { Info } from 'react-feather';

import StarsIcon from '@/app/img/icons/stars.svg';

import type { AutocompleteItem } from '../model/account-autocomplete/types';

export interface AccountInputProps extends React.ComponentProps<'input'> {
    account: InstructionAccountData;
    error: { message?: string | undefined } | undefined;
    autocompleteItems?: AutocompleteItem[];
    seeds: { name: string }[];
}

// FIXME: missing Storybook story — pure props (InstructionAccountData + autocomplete items), could be storied with fixtures.
export const AccountInput = forwardRef<
    HTMLInputElement,
    Omit<AccountInputProps, 'onChange'> & {
        // This type serves as an intermediary between the autocomplete component and the react-hook-form component
        onChange: (value: { target: { value: string }; currentTarget: { value: string } }) => void;
    }
>(({ account, error, onChange, autocompleteItems = [], seeds, ...props }, ref) => {
    const [inputId, setInputId] = useState('');

    return (
        <div className="space-y-2">
            <div className="flex items-center gap-2">
                <Label className="text-sm font-normal text-neutral-200" htmlFor={inputId}>
                    {account.name}
                </Label>
                <div className="flex gap-1">
                    {account.writable && (
                        <Badge variant="warning" size="xs">
                            Mutable
                        </Badge>
                    )}
                    {account.signer && (
                        <Badge variant="warning" size="xs">
                            Signer
                        </Badge>
                    )}
                    {account.pda && (
                        <Tooltip>
                            <TooltipTrigger asChild>
                                <div className="inline-flex cursor-default items-center">
                                    <Badge variant="info" size="xs">
                                        PDA
                                        <Info className="h-4 w-4" />
                                    </Badge>
                                </div>
                            </TooltipTrigger>
                            <TooltipContent>
                                <div className="min-w-40 max-w-full">
                                    Can be generated from the next arguments:
                                    <div className="text-teal-400">{seeds.map(seed => seed.name).join(', ')}</div>
                                </div>
                            </TooltipContent>
                        </Tooltip>
                    )}
                    {account.optional && (
                        <Badge variant="secondary" size="xs">
                            Optional
                        </Badge>
                    )}
                </div>
            </div>
            <Autocomplete
                items={autocompleteItems}
                value={String(props.value)}
                renderItemContent={option => <AutocompleteItemContent option={option} seeds={seeds} />}
                onChange={value => {
                    onChange({
                        currentTarget: { value },
                        target: { value },
                    });
                }}
                inputProps={{
                    'aria-invalid': Boolean(error),
                    ref,
                    variant: 'dark',
                }}
                onInputIdReady={setInputId}
            />
            {account.docs.length > 0 && <p className="text-xs text-neutral-400">{account.docs.join(' ')}</p>}
            {error && <p className="mt-1 text-xs text-destructive">{error.message}</p>}
        </div>
    );
});

AccountInput.displayName = 'AccountInput';

function AutocompleteItemContent({ option, seeds }: { option: AutocompleteItem; seeds: { name: string }[] }) {
    return (
        <div className="flex w-full flex-col items-start justify-between gap-1 px-4 py-1.5 text-xs">
            <span className="text-xs font-medium text-heavy-metal-300">
                {option.label}
                {option.generated && (
                    <Image
                        src={StarsIcon}
                        alt="Account autogenerated PDA"
                        height={16}
                        width={16}
                        className="ml-2 inline"
                    />
                )}
            </span>

            <span className="w-full break-all font-mono text-[11px] text-heavy-metal-400">
                {option.value || 'Enter all required arguments to generate PDA'}
            </span>

            {option.generated && option.value && (
                <div className="text-[10px] text-heavy-metal-500">
                    Arguments: {seeds.map(seed => seed.name).join(', ')}
                </div>
            )}
        </div>
    );
}
