name: CI

on:
  push:
    branches: [master]

env:
  # cash folder for pnpm_store, nextjs and playwright later on
  PW_CACHE_AFFIX: pw
  PW_CACHE_FOLDER: ~/.cache/ms-playwright
  PNPM_CACHE_FOLDER: ~/.pnpm-store

jobs:
  static-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      DUNE_PROGRAM_STATS_MV_ID: ${{ vars.DUNE_PROGRAM_STATS_MV_ID }}
      DUNE_PROGRAM_CALLS_MV_ID: ${{ vars.DUNE_PROGRAM_CALLS_MV_ID }}
      CRON_SECRET: ${{ vars.CRON_SECRET }}

    strategy:
      matrix:
        node-version: ['${{ needs.read-nvmrc.outputs.node-version }}']

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install package manager
        uses: pnpm/action-setup@v4

      # Configure pnpm store directory BEFORE setup-node tries to cache it
      - name: Setup pnpm config
        run: pnpm config set store-dir ${{ env.PNPM_CACHE_FOLDER }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup Additional Cache
        uses: actions/cache@v4
        id: additional_cache
        with:
          path: |
            ${{ env.PNPM_CACHE_FOLDER }}
            ${{ env.PW_CACHE_FOLDER }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ env.PW_CACHE_AFFIX }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/.browserslistrc') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PW_CACHE_AFFIX }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-${{ env.PW_CACHE_AFFIX }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Code-style
        run: pnpm format:ci

      - name: Test
        env:
          TEST_SERIAL_TIMEOUT: ${{ vars.TEST_SERIAL_TIMEOUT }}
        run: |
          pnpm test:ci

      - name: Database migration
        run: NODE_ENV=production pnpm drizzle-kit migrate

      - name: Trigger Vercel Deploy
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
